apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker
  namespace: citus
spec:
  serviceName: citus-worker
  replicas: 2
  selector:
    matchLabels:
      app: citus-worker
  template:
    metadata:
      labels:
        app: citus-worker
    spec:
      containers:
      - name: worker
        image: citusdata/citus:12.0
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  namespace: citus
spec:
  clusterIP: None
  selector:
    app: citus-worker
  ports:
  - port: 5432
    targetPort: 5432
