apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-coordinator
  namespace: citus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus-coordinator
  template:
    metadata:
      labels:
        app: citus-coordinator
    spec:
      containers:
      - name: coordinator
        image: citusdata/citus:12.0
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: CITUS_WORKER_NODES
          value: "citus-worker-0.citus-worker,citus-worker-1.citus-worker"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
  namespace: citus
spec:
  selector:
    app: citus-coordinator
  ports:
  - port: 5432
    targetPort: 5432
